Add 'Dropdowns' page
jenkinsci/design-library-plugin pull request #311
Opened 2024-02-10 13:20 UTC by janfaracik

![Screenshot 2024-02-10 at 13 18 51](https://github.com/jenkinsci/design-library-plugin/assets/43062514/01ce898f-b238-4899-a886-88185939bec4)

Adds a page on dropdowns. 

Note - Will need to be updated for https://github.com/jenkinsci/jenkins/pull/8827

### Testing done

```[tasklist]
### Submitter checklist
- [x] Make sure you are opening from a **topic/feature/bugfix branch** (right side) and not your main branch!
- [x] Ensure that the pull request title represents the desired changelog entry
- [x] Please describe what you did
- [x] Link to relevant issues in GitHub or Jira
- [x] Link to relevant pull requests, esp. upstream and downstream changes
- [x] Ensure you have provided tests - that demonstrates feature works or fixes the issue
```

2024-02-10 19:31 UTC, janfaracik commented on pom.xml
> +        <jenkins.version>2.445-rc34653.8b_944e9e3fe9</jenkins.version>
TODO - Revert before merge

2024-02-10 22:01 UTC, timja approved these changes

2024-03-11 11:52 UTC, daniel-beck requested changes
Lacks `dd:custom` example.

2024-03-11 11:52 UTC, daniel-beck commented on src/main/resources/io/jenkins/plugins/designlibrary/Dropdowns/index.properties
> +do.2=Use dropdowns to offer quick access to a subpage's actions
```suggestion
do.2=Use dropdowns to offer quick access to a subpage''s actions
```

2024-03-11 21:45 UTC, daniel-beck approved these changes
Looks reasonable. Untested.

2024-03-26 10:10 UTC, merged